hash-format = "sha256"

[[files]]
file = "README.md"

[[files]]
file = "config/AppleCore.cfg"

[[files]]
file = "config/AppliedEnergistics2/AppliedEnergistics2.cfg"

[[files]]
file = "config/AppliedEnergistics2/CustomRecipes.cfg"

[[files]]
file = "config/AppliedEnergistics2/Facades.cfg"

[[files]]
file = "config/AppliedEnergistics2/VersionChecker.cfg"

[[files]]
file = "config/AquaTweaks.cfg"

[[files]]
file = "config/Automagy.cfg"

[[files]]
file = "config/Baubles.cfg"

[[files]]
file = "config/BiblioCraft.cfg"

[[files]]
file = "config/Botania.cfg"

[[files]]
file = "config/CarpentersBlocks.cfg"

[[files]]
file = "config/CodeChickenCore.cfg"

[[files]]
file = "config/DLDungeonsJBG/DLDungeonsJBG.cfg"

[[files]]
file = "config/DLDungeonsJBG/chests.cfg"

[[files]]
file = "config/DLDungeonsJBG/nbt.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/common.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/continentalShelf.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/dank.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/desert.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/frozen.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/jungle.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/mesa.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/nether.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/oceanic.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/template.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/urban.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/villagelike.cfg"

[[files]]
file = "config/DLDungeonsJBG/themes/volcanic.cfg"

[[files]]
file = "config/ExtraTiC.cfg"

[[files]]
file = "config/ForbiddenMagic.cfg"

[[files]]
file = "config/ForgeRelocation.cfg"

[[files]]
file = "config/ForgottenRelics.cfg"

[[files]]
file = "config/HardcoreDarkness.cfg"

[[files]]
file = "config/HardcoreEnderExpansion.cfg"

[[files]]
file = "config/HardcoreEnderExpansion.clientsave.cfg"

[[files]]
file = "config/InfernalMobs.cfg"

[[files]]
file = "config/LegibleNei/LegibleNei.cfg"

[[files]]
file = "config/LegibleNei/LegibleNei.json"

[[files]]
file = "config/LegibleNei/LegibleNei.log"

[[files]]
file = "config/LegibleNei/filters/Bibliocraft.json"

[[files]]
file = "config/LegibleNei/filters/BloodMagic.json"

[[files]]
file = "config/LegibleNei/filters/Botania.json"

[[files]]
file = "config/LegibleNei/filters/Buildcraft.json"

[[files]]
file = "config/LegibleNei/filters/Chisel.json"

[[files]]
file = "config/LegibleNei/filters/Decocraft.json"

[[files]]
file = "config/LegibleNei/filters/EnderIO.json"

[[files]]
file = "config/LegibleNei/filters/Extrautilities.json"

[[files]]
file = "config/LegibleNei/filters/Forestry.json"

[[files]]
file = "config/LegibleNei/filters/ForgeMicroblock.json"

[[files]]
file = "config/LegibleNei/filters/Harvest.json"

[[files]]
file = "config/LegibleNei/filters/Magicalcrops.json"

[[files]]
file = "config/LegibleNei/filters/Mekanism.json"

[[files]]
file = "config/LegibleNei/filters/Netherlicious.json"

[[files]]
file = "config/LegibleNei/filters/Openblock.json"

[[files]]
file = "config/LegibleNei/filters/Orespawn.json"

[[files]]
file = "config/LegibleNei/filters/Thaumcraft.json"

[[files]]
file = "config/LegibleNei/filters/ThaumicEnergistics.json"

[[files]]
file = "config/LegibleNei/filters/Thermal.json"

[[files]]
file = "config/LegibleNei/filters/Tinker.json"

[[files]]
file = "config/LegibleNei/filters/VillageNames.json"

[[files]]
file = "config/LegibleNei/filters/Yegamol.json"

[[files]]
file = "config/LegibleNei/filters/Ztones.json"

[[files]]
file = "config/LegibleNei/filters/appliedenergistics2.json"

[[files]]
file = "config/LegibleNei/filters/minecraft.json"

[[files]]
file = "config/MCFrames.cfg"

[[files]]
file = "config/ModernKeyBinding.cfg"

[[files]]
file = "config/Morpheus.cfg"

[[files]]
file = "config/MouseTweaks.cfg"

[[files]]
file = "config/MrTJPCore.cfg"

[[files]]
file = "config/NEI/client.cfg"

[[files]]
file = "config/NEI/handlerordering.csv"

[[files]]
file = "config/NEI/heighthackhandlers.cfg"

[[files]]
file = "config/NEI/serialhandlers.cfg"

[[files]]
file = "config/NEIAddons.cfg"

[[files]]
file = "config/Natura-Dynamic.json"

[[files]]
file = "config/Natura.cfg"

[[files]]
file = "config/Netherlicious/Armor_Tool_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Biome_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Biome_Sound_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Crop_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Entity_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Main_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Particle_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Piglin_Sell_List.cfg"

[[files]]
file = "config/Netherlicious/Structure_Configuration.cfg"

[[files]]
file = "config/Netherlicious/Worldgeneration_Configuration.cfg"

[[files]]
file = "config/OpenBlocks.cfg"

[[files]]
file = "config/OpenMods.cfg"

[[files]]
file = "config/OpenModsLibCore.json"

[[files]]
file = "config/ProjectRed.cfg"

[[files]]
file = "config/SlimeKnights/Mantle.cfg"

[[files]]
file = "config/SpecialMobs.cfg"

[[files]]
file = "config/StorageDrawers.cfg"

[[files]]
file = "config/TaintedMagic.cfg"

[[files]]
file = "config/Thaumcraft.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/Automagy.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/BiblioCraft.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/BiomesOPlenty.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/Botania.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/CarpentersBlocks.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/ForgottenRelics.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/HardcoreEnderExpansion.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/Natura.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/OpenBlocks.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/OpenMods.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/SpecialMobs.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/TConstruct.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/TaintedMagic.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/Thaumcraft.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/ThaumicExploration.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/ThaumicHorizons.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/ThaumicTinkerer.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/TwilightForest.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/VillageNames.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/WitchingGadgets.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/aetherlegacy.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/appliedenergistics2.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/chisel.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/cuchaz.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/dmod.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/etfuturum.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/hardcorewither.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/makeo.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/mowziesmobs.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/net.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/netherlicious.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/thejungle.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/unknown.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/vanilla.cfg"

[[files]]
file = "config/ThaumcraftMobAspects/vanillaitem.cfg"

[[files]]
file = "config/ThaumicExploration.cfg"

[[files]]
file = "config/ThaumicHorizons.cfg"

[[files]]
file = "config/ThaumicTinkerer.cfg"

[[files]]
file = "config/TravellersGear.cfg"

[[files]]
file = "config/TravellersGear_inv.cfg"

[[files]]
file = "config/TwilightForest.cfg"

[[files]]
file = "config/UniDict.cfg"

[[files]]
file = "config/UpdateCheckLib.cfg"

[[files]]
file = "config/VillageNames4/general.cfg"

[[files]]
file = "config/VillageNames4/namepieces/alien.cfg"

[[files]]
file = "config/VillageNames4/namepieces/alienvillage.cfg"

[[files]]
file = "config/VillageNames4/namepieces/angel.cfg"

[[files]]
file = "config/VillageNames4/namepieces/custom.cfg"

[[files]]
file = "config/VillageNames4/namepieces/demon.cfg"

[[files]]
file = "config/VillageNames4/namepieces/dragon.cfg"

[[files]]
file = "config/VillageNames4/namepieces/endcity.cfg"

[[files]]
file = "config/VillageNames4/namepieces/fortress.cfg"

[[files]]
file = "config/VillageNames4/namepieces/goblin.cfg"

[[files]]
file = "config/VillageNames4/namepieces/golem.cfg"

[[files]]
file = "config/VillageNames4/namepieces/mansion.cfg"

[[files]]
file = "config/VillageNames4/namepieces/mineshaft.cfg"

[[files]]
file = "config/VillageNames4/namepieces/monument.cfg"

[[files]]
file = "config/VillageNames4/namepieces/pet.cfg"

[[files]]
file = "config/VillageNames4/namepieces/stronghold.cfg"

[[files]]
file = "config/VillageNames4/namepieces/temple.cfg"

[[files]]
file = "config/VillageNames4/namepieces/village.cfg"

[[files]]
file = "config/VillageNames4/namepieces/villager.cfg"

[[files]]
file = "config/VillageNames4/newvillages/village_gen.cfg"

[[files]]
file = "config/Waila.cfg"

[[files]]
file = "config/WailaHarvestability.cfg"

[[files]]
file = "config/WitchingGadgets.cfg"

[[files]]
file = "config/archaicfix.cfg"

[[files]]
file = "config/aroma1997/Aroma1997Core.cfg"

[[files]]
file = "config/aroma1997/AromaBackup.cfg"

[[files]]
file = "config/aroma1997/AromaBackupRecovery.cfg"

[[files]]
file = "config/bbm/AI_Improvements.cfg"

[[files]]
file = "config/biomesoplenty/biomegen.cfg"

[[files]]
file = "config/biomesoplenty/biomeweights.cfg"

[[files]]
file = "config/biomesoplenty/ids.cfg"

[[files]]
file = "config/biomesoplenty/main.cfg"

[[files]]
file = "config/biomesoplenty/misc.cfg"

[[files]]
file = "config/biomesoplenty/structures/strongholds.cfg"

[[files]]
file = "config/biomesoplenty/structures/villages.cfg"

[[files]]
file = "config/biomesoplenty/terraingen.cfg"

[[files]]
file = "config/bugtorch/base.cfg"

[[files]]
file = "config/bugtorch/mixins.cfg"

[[files]]
file = "config/bugtorch/mixinsModSupport.cfg"

[[files]]
file = "config/bugtorch/modSupport.cfg"

[[files]]
file = "config/chisel.cfg"

[[files]]
file = "config/cofh/core/client.cfg"

[[files]]
file = "config/cofh/core/common.cfg"

[[files]]
file = "config/cofh/core/friends.cfg"

[[files]]
file = "config/cofh/core/loot.cfg"

[[files]]
file = "config/cofh/world/Vanilla.json"

[[files]]
file = "config/coretweaks.cfg"

[[files]]
file = "config/defaultworldgenerator.cfg"

[[files]]
file = "config/dmod.cfg"

[[files]]
file = "config/dsurround/dsurround.cfg"

[[files]]
file = "config/endercore/cropConfig.json"

[[files]]
file = "config/endercore/endercore.cfg"

[[files]]
file = "config/etfuturum/blocksitems.cfg"

[[files]]
file = "config/etfuturum/enchantspotions.cfg"

[[files]]
file = "config/etfuturum/entities.cfg"

[[files]]
file = "config/etfuturum/functions.cfg"

[[files]]
file = "config/etfuturum/mixins.cfg"

[[files]]
file = "config/etfuturum/tweaks.cfg"

[[files]]
file = "config/etfuturum/world.cfg"

[[files]]
file = "config/falsepatternlib.cfg"

[[files]]
file = "config/falsetweaks.cfg"

[[files]]
file = "config/falsetweaks_userspecific.cfg"

[[files]]
file = "config/fastcraft.ini"

[[files]]
file = "config/flyingcullers.cfg"

[[files]]
file = "config/forge.cfg"

[[files]]
file = "config/forgeChunkLoading.cfg"

[[files]]
file = "config/gadomancy.cfg"

[[files]]
file = "config/gravestone.cfg"

[[files]]
file = "config/hardcorewither.cfg"

[[files]]
file = "config/harvestcraft.cfg"

[[files]]
file = "config/immersive_snow.cfg"

[[files]]
file = "config/immersivecavegen.cfg"

[[files]]
file = "config/journeymap_ModInfo.cfg"

[[files]]
file = "config/journeymap_api_1.7.10.cfg"

[[files]]
file = "config/microblocks.cfg"

[[files]]
file = "config/mixingasm/transformer_exclusion_list.txt"

[[files]]
file = "config/mixingasm/transformer_inclusion_list.txt"

[[files]]
file = "config/mixingasm/transformer_inclusion_list_default.txt"

[[files]]
file = "config/mowziesmobs.cfg"

[[files]]
file = "config/multipart.cfg"

[[files]]
file = "config/neiintegration.cfg"

[[files]]
file = "config/neodymium.cfg"

[[files]]
file = "config/reccomplex.cfg"

[[files]]
file = "config/roguelike_dungeons/roguelike.cfg"

[[files]]
file = "config/satchels.cfg"

[[files]]
file = "config/sloppydeploader.cfg"

[[files]]
file = "config/soundfilters.cfg"

[[files]]
file = "config/splash.properties"

[[files]]
file = "config/tc4tweak.cfg"

[[files]]
file = "config/tcneiadditions.cfg"

[[files]]
file = "config/tcnodetracker.cfg"

[[files]]
file = "config/thaumcraftneiplugin.cfg"

[[files]]
file = "config/thaumicenergistics.cfg"

[[files]]
file = "config/thejungleMod.cfg"

[[files]]
file = "config/wailaplugins.cfg"

[[files]]
file = "mods/1.7.10/Baubles-1.7.10-1.0.1.14.jar"

[[files]]
file = "mods/1.7.10/CodeChickenLib-1.7.10-1.1.5.5.jar"

[[files]]
file = "mods/CodeChickenCore-1.7.10-1.1.5.jar"

[[files]]
file = "mods/CoreTweaks-1.7.10-0.2.6_3+nomixin.jar"

[[files]]
file = "mods/Forbidden.Magic-1.7.10-0.6-GTNH.jar"

[[files]]
file = "mods/HardcoreEnderExpansion-MC-1.7.10-v1.8.8-GTNH.jar"

[[files]]
file = "mods/NEIAddons-1.7.10-1.12.22.jar"

[[files]]
file = "mods/NEIIntegration-1.7.10-1.2.3.jar"

[[files]]
file = "mods/OptiFine_1.7.10_HD_U_D6.jar"

[[files]]
file = "mods/StorageDrawers-1.7.10-1.11.19-GTNH.jar"

[[files]]
file = "mods/StorageDrawersBop-1.7.10-1.11.17-GTNH.jar"

[[files]]
file = "mods/Tainted-Magic-1.7.10-8.1.1.1-GTNH.jar"

[[files]]
file = "mods/ThaumcraftMobAspects-1.7.10-1.0.0-GTNH.jar"

[[files]]
file = "mods/Thaumic-Dyes-.1.7.10.1.10.6-0.jar"

[[files]]
file = "mods/Thaumic-Exploration-.1.7.10.1.1.83-LE-0.jar"

[[files]]
file = "mods/ThaumicHorizons-1.7.10-1.2.1.8.jar"

[[files]]
file = "mods/ThaumicTinkerer-1.7.10-2.6.5LE-5-gab5e365.dirty.jar"

[[files]]
file = "mods/WAILAPlugins-1.7.10-0.2.5.jar"

[[files]]
file = "mods/Waila-1.7.10-1.5.21.jar"

[[files]]
file = "mods/WailaHarvestability-1.7.10-1.1.10-GTNH.jar"

[[files]]
file = "mods/WitchingGadgets-1.7.10-1.2.9LE.jar"

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/appliedenergistics2-1.7.10-rv3-beta-118-GTNH.jar"

[[files]]
file = "mods/archaicfix.pw.toml"
metafile = true

[[files]]
file = "mods/aroma1997core.pw.toml"
metafile = true

[[files]]
file = "mods/aromabackup.pw.toml"
metafile = true

[[files]]
file = "mods/automagy.pw.toml"
metafile = true

[[files]]
file = "mods/betterfps.pw.toml"
metafile = true

[[files]]
file = "mods/biome-decoration-fix.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/bop-quicksand-reducer.pw.toml"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
metafile = true

[[files]]
file = "mods/bugtorch-1.7.10-1.1.8.jar"

[[files]]
file = "mods/chisel-1.7.10-2.10.4-GTNH.jar"

[[files]]
file = "mods/cofh-core.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
metafile = true

[[files]]
file = "mods/default-world-generator.pw.toml"
metafile = true

[[files]]
file = "mods/endercore-1.7.10-1.0.jar"

[[files]]
file = "mods/et-futurum-requiem.pw.toml"
metafile = true

[[files]]
file = "mods/falsetweaks.pw.toml"
metafile = true

[[files]]
file = "mods/fastcraft.pw.toml"
metafile = true

[[files]]
file = "mods/flying-cullers.pw.toml"
metafile = true

[[files]]
file = "mods/forgotten-relics.pw.toml"
metafile = true

[[files]]
file = "mods/fplib.pw.toml"
metafile = true

[[files]]
file = "mods/fullscreen-windowed-borderless-for-minecraft.pw.toml"
metafile = true

[[files]]
file = "mods/gadomancy-1.7.10-1.0.8.3.jar"

[[files]]
file = "mods/gasstation.pw.toml"
metafile = true

[[files]]
file = "mods/gravestone-1.7.10-1.1.0.jar"

[[files]]
file = "mods/hardcore-wither.pw.toml"
metafile = true

[[files]]
file = "mods/inventorytweaks-1.7.10-1.5.15.jar"

[[files]]
file = "mods/ivtoolkit.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/legiblenei.pw.toml"
metafile = true

[[files]]
file = "mods/modtweaker.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mysteriumlib.pw.toml"
metafile = true

[[files]]
file = "mods/neodymium-1.7.10-0.1.5.jar"

[[files]]
file = "mods/neodymium.pw.toml"
metafile = true

[[files]]
file = "mods/netherlicious.pw.toml"
metafile = true

[[files]]
file = "mods/notenoughitems-gtnh.pw.toml"
metafile = true

[[files]]
file = "mods/project-74246.pw.toml"
metafile = true

[[files]]
file = "mods/reauth.pw.toml"
metafile = true

[[files]]
file = "mods/recurrent-complex-unofficial.pw.toml"
metafile = true

[[files]]
file = "mods/roguelike-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/tc4tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/tcneiadditions-1.7.10-1.1.1.7.dirty.jar"

[[files]]
file = "mods/tcnodetracker-1.7.10-1.1.6.jar"

[[files]]
file = "mods/thaumcraft-inventory-scanning.pw.toml"
metafile = true

[[files]]
file = "mods/thaumcraft-nei-plugin.pw.toml"
metafile = true

[[files]]
file = "mods/thaumcraft.pw.toml"
metafile = true

[[files]]
file = "mods/thaumicenergistics-1.7.10-1.3.21-GTNH.jar"

[[files]]
file = "mods/travellers-gear.pw.toml"
metafile = true

[[files]]
file = "mods/village-names.pw.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "optionsof.txt"

[[files]]
file = "packwiz-installer-bootstrap.jar"

[[files]]
file = "packwiz-installer.jar"

[[files]]
file = "scripts/BotaniaAspects.zs"

[[files]]
file = "scripts/Symbiotic+Botania-245+and+Thaumcraft-4.2.3.5.zs"

[[files]]
file = "scripts/removeunusedshit.zs"
