name = "NewThaum"
author = "Jerome226"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30de1113fcf8f2265fc5dd7d2278483d769df680d8beee9ee3e8f65ea5e06be5"

[versions]
forge = "10.13.4.1614-1.7.10"
minecraft = "1.7.10"
