name = "NewThaum"
author = "Jerome226"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db1cb7a0fd62593a426f78447e498d908b7a184d677a0b6ec6e3d62ca5f14a3"

[versions]
forge = "10.13.4.1614-1.7.10"
minecraft = "1.7.10"
